### ISSUE TITLE
exclude moment from bundle by default?

### ISSUE THREAD

**Issue by mojoaxel** [visjs/vis-timeline#12]
Since #9 it is possible to exclude external libraries (e.g. moment) from the build.
The question is should be exclude e.g. `moment` by default? This would be a breaking change because than the user would always need to import `moment` manually.

What do you folks think?

**Comment by yotamberk** [comment]
TBH, I think we're better off keeping the dependency of moment.js.
Our project is quite dependent on this module. I think we should close this issue since it doesn;t seem to be one to me

**Comment by mojoaxel** [comment]
Well, there a a lot of projects that already include moment.js So the this really big library gets included twice. We could create a seperate `vis-timeline.pure.min.js` bundle without moment.js !?

**Comment by bladerunner41** [comment]
I assume this is only for the pre-bundled *.js files - if using a modern framework with ES6 imports via npm it should be de-duplicated anyway?  

I assume these days the .js files would only be used by novices or for quick starts and so should include all dependencies to run?

I note hammer.js is also a dependency – similar considerations.

**Comment by mojoaxel** [comment]
I guess you are right. If somebody uses the vis-timeline in there own propjekt that can/should create their own bundle based on our ESM bundle. 
Maybe we should add some infos on how to do that in the README? Or maybe even a rollup or webpack demo-Projekt?

**Comment by bladerunner41** [comment]
Just looked at the README.  Yes - as it only lists `npm install` it should probably give an example how to import/require the code when using a module builder or vanilla javascript like most librarys - don't think you need to write code in a /examples folder.  

Just a quick example below - could strucutre it any way - details probably not correct - I am only new to this.

# Install
Install via npm:
```
$ npm install vis-timeline
```
## When using ES6 or commonJS modules:

### Javascript file:
````
//When using ES6:
import * as vis from 'vis';

//When using commonJS:
const vis = require('vis');
````
### HTML file:
You will need to include the .css styles manually (I belive so - only new here):
```
<head>
  <link href="../../dist/vis-timeline-graph2d.css" rel="stylesheet" type="text/css" />
  <!--or use the CDN hosted (minified production build)-->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis.css">
</head>
```

## When using vanillia Javascript:
```
<head>
  <script src="../../dist/vis-timeline-graph2d.js"></script>
  <link href="../../dist/vis-timeline-graph2d.css" rel="stylesheet" type="text/css" />

  <!--or use the CDN hosted (minified production build)-->

  <script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis-timeline-graph2d.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis.css">
</head>
```

## Example project wrappers
* Angular: [ngx-vis](https://github.com/hypery2k/ngx-vis) (Timline & Graph)

**Comment by mojoaxel** [comment]
@bladerunner41 Thank you! This would be a nice addition!
I want to encourage you to create a simple pull-request that changes the README.md. Ideally fork the repository and create a new feature-branch for this. Than we can together find the perfect wording for this. :rocket:

**Comment by bladerunner41** [comment]
Thanks @mojoaxel will do.

**Comment by MartinManev** [comment]
Hi,

I want to inquire about the bundle size. I am using Vue/Vue CLI, which uses webpack, and after importing 'vis-timeline' (vis-timeline-graph2d.esm.js), webpack bundle analyzer shows 1.42 MB (stat size), 552.44 KB (parsed size) and 156.58 KB (gzipped size). This is by far the largest package in my app.

Is it possible to reduce the bundle size? The packages `core-js`, `moment` and `hammerjs` seem like the big ones. I am already importing `core-js` in my app, so I end up with another copy of the dependency. It was the same with `moment`, but I removed it from my `package.json` to avoid this problem. The thing is, I don't really want to couple my app with `moment` - I might want to use another package instead. I also don't like that `vis-timeline` has these built-in AND locked to a specific version. So even if I am going to use moment anyways, then I must use the same version that `vis-timeline` uses.

Another thing for `moment`: I definitely want to exclude all the built-in locales and provide my own.

In any case, I am also looking for tips on how to optimize the bundle size. How are you guys using `vis-timeline` in your projects? Do I need to import it in a different way and not use the pre-bundled files? How would I go about doing that?

Testing with vis-timeline version 6.0.2

**Comment by mojoaxel** [comment]
We should create an additional bundle without moment!

**Comment by yotamberk** [comment]
@Thomaash Now that we have type coercion, is this still an issue? What do we need to do to remove dependencies of `Moment` in this project? Simply removing it from the dependencies?

**Comment by Thomaash** [comment]
Simple removal of Moment from the dependencies followed by a complete overhaul of the way dates are handled throughout the whole project :smile:.

I thinks we should and I plan to create a peer build which would have Moment as one of it's peer dependencies (so that people would supply one Moment for their whole app instead of having one in app and another one in Timeline) and standalone build which would have it bundled. This is exactly the way we already have it in Vis Network and it would also be a part of the solution to #67.

Although given what @MartinManev said we should maybe rethink the way we do things here. Because we really do pack a lot of stuff into this. Maybe providing something without polyfills and all the locales etc. so that people could get just what they need and transpile it to suit their needs. I see a lot of work and breaking changes here though.

**Comment by Thomaash** [comment]
A note for @MartinManev since I already mentioned you here. #269 will introduce peer build which will come without locales. However getting rid of Moment altogether and Hammer would require big overhaul of this project.

**Comment by bladerunner41** [comment]
Luxon is a new modern version of Moment.js by the creator of Moment which has no locale or timezone data bundles required for modern browsers (polly fill's available).  

The API is different, as per this [migration guide] for moment users (https://moment.github.io/luxon/docs/manual/moment.html)

**Comment by Async0x42** [comment]
Another alternative to think about if removing moment could be date-fns.

https://date-fns.org

**Comment by Thomaash** [comment]
I used date-fns before. It's great since it's just a bunch of functions so we would pick what we need without bloating the bundle.

Luxon seems like yet another Moment to me. I don't see any point in switching to that. I've never used it though so I may be wrong.

**Comment by Async0x42** [comment]
> I used date-fns before. It's great since it's just a bunch of functions so we would pick what we need without bloating the bundle.

Agreed, I'm really only using Moment because it's embedded within visjs, if it wasn't then I'd definitely go back to date-fns

**Comment by MartinManev** [comment]
This is what the rollup visualizer plugin shows. It is an HTML file, but i've renamed it to .txt so GitHub can accept it.
[stats.txt](https://github.com/visjs/vis-timeline/files/4127437/stats.txt)
I'm not sure what version of vis-timeline this is, but I just pulled the master branch.
The total bundle size is 1.55 MB.
The size of the dependencies in node_modules is ~925 KB which is 58.14%.
Here are some stats for the dependencies:
vis-data - 435.58 KB (27.39% of total)
moment - 165.01 KB (10.38% of total)
vis-util - 132.15 KB (8.31% of total)
core-js-pure - 95.96 KB (6.03% of total)
hammer.js - 73.27 KB (4.61% of total)
and some other very minor dependencies

1. Since vis-data and vis-util come as a bundle I have a suspicion that they include their own copies of the dependencies. I'm not entirely sure how the bundling process works so I might be wrong on this. It would be reassuring if someone could check if this is true or not.
2. I don't know if it is a good decision to remove moment entirely, but setting it as a peer dependency seems like the way to go. Being able to choose what version or locales I want to use is perfect. Also, I might want to use moment-timezone which includes moment. The reason I said that I might want to use another library (like the mentioned Luxon or date-nfs) is because there is a problem with the recent versions of moment-timezone, where the timezone data range is greatly reduced.
3. The polyfill problem: I believe the idea is that libraries do not include polyfills since they are not aware of the environment that the app is going to be run in. That is a job for the bundler (e.g. Webpack or Rollup) where you can configure what browsers you want to support and include only the polyfills that are necessary. For standalone use of vis-timeline you could include a separate script that can be imported and includes the necessary polyfills for whatever browsers the user wants to support.

Thats all for now. I'm glad that this issue is still being considered.

**Comment by Thomaash** [comment]
Hi @MartinManev,

Regarding numbers 1 and 3: I decided to include ESNext builds without bundled dependencies in all of our projects (it will take a while though).

When it comes to number 2: I think it would be a good idea to switch to date-fns. Looking through the code it sometimes uses Moment, sometimes native Date and sometimes plain number representing milliseconds since the Unix epoch. Seems like quite a mess. Replacing Moment by native Date plus date-fns could be an improvement in both bundle size and consistency. This is more of a thing for @yotamberk though.
