### ISSUE TITLE
Merge with timeline-plus project

### ISSUE THREAD

**Issue by jarnovanrhijn** [visjs/vis-timeline#150]
Hi,

I've got a question regarding the merge which has been done with timeline-plus. I'm not seeing any of the performance imrovements made in timeline-plus (e.g. repainting due to the use of top/right/bottom/left instead of using css transforms.). Am i missing something or is it not merged on purpose (yet)?

Thanks :) for all the great work!!

**Comment by yotamberk** [comment]
OMG! I have no idea how this happened but somehow the PR with your improvements of the performance https://github.com/yotamberk/timeline-plus/pull/168 did not make it to my merge 😱 
I have no idea how that happened since I'm sure I did it! 
I will investigate what happened... I will re-implement what you've done if needed and give you the credit...

**Comment by jarnovanrhijn** [comment]
Haha no need for credits (you did gave them in the release notes 😂)

Just wanted to make sure everything was merged properly! Thanks for the reply and hopefully see the merge soon 😁

**Comment by jarnovanrhijn** [comment]
AWESOME!! Thanks for the quick PR! Everything looks great as far as i can see!

**Comment by yotamberk** [comment]
@jarnovanrhijn I've noticed something wrong with this PR. in the `rtl.html` example, the point item is misbehaving... I've been comparing this PR with yours and I can't find the difference... 
Can you take a look and help me find what I did wrong?
