### ISSUE TITLE
Timeline not loading due to 'Object expected'-error in IE11

### ISSUE THREAD

**Issue by pwlinkas** [visjs/vis-timeline#243]
### Error
In IE11 I get the error `Object expected` on line 20 in Range.js. Looks like `moment` is undefined.

    const now = moment().hours(0).minutes(0).seconds(0).milliseconds(0);

### Steps to reproduce
1. Open [the basic example](https://visjs.github.io/vis-timeline/examples/timeline/basicUsage.html) in IE11
2. Timeline not loading due to error above

I can't find any list of supported browsers for vis-timeline, so I'm not sure if IE11 is supposed to be supported anymore.

**Comment by Async0x42** [comment]
I haven't looked into it yet, but the latest version (6.3.5) breaks IE11 support for me. 6.3.4 seems to work in IE11.

**Comment by Thomaash** [comment]
My untested theory:

- Vis Util had IE11 issues until 2.0.1, Timeline uses 1.1.4.
- Vis Data had IE11 issues until 6.2.4, Timeline uses 6.1.1.

With Timeline 6.3.5 prototype pollution was removed which most likely caused these issues. The pollution provided missing polyfills for these versions and since it is no longer present it just doesn't work.

Simply updating dependencies or providing global polyfills could resolve this issue.

**Comment by fras2560** [comment]
@Thomaash I encountered the similar issue. I updated both Vis Util and Vis Data to the recommended versions and it seemed to resolve the IE 11 issues. I encountered.
