### ISSUE TITLE
Please do not deprecate the Legacy build

### ISSUE THREAD

**Issue by jladbury** [visjs/vis-timeline#395]
I have been using vis timeline for many years, in a project that was designed and written before JavaScript modules. One day, I will get round to amending them to the new modular way of doing things.

Yesterday I spent far too long trying to update from my old 4.21 to 7.3.4, mostly because of packaging reasons. At first I heeded the plea  about the Legacy build ('please do not use this') and tried to shoehorn the Peer and other builds into my project, but this proved not be be a trivial task. In contrast, I finally dropped in the Legacy build and upgraded without problem.

Please do not deprecate it!

**Comment by yotamberk** [comment]
This issue is not exactly useful... If you have an issue upgrading the version of vis-timeline, post a new issue explaining what are the issues you're encountering, and we (maintainers and public) can help you solve them. 

Requesting not to deprecate the legacy version is not exactly an relevant issue.

In any case, we are not planning to deprecate it anytime soon. We are simply declaring this version will not be supported by us if at some point that version stops working (or causes issues only that bundle is producing). We highly advise to move to the newer version and bundles since they solve many other issues (previous and upcoming).

**Comment by jladbury** [comment]
Just in case anyone else ever finds themselves in the position I did  . . . 
 
I revisited using one of the approved builds and succeeded in installing the 'Browser UMD' version of the Peer build. By 'installing', I mean a straight library replacement of the old Almende one.

The problems I failed to report in detail resulting in yotamberk's 'This issue is not exactly useful' comment were largely historical due to my use of Typescript, which did not at the time play well with a mix of old-fashioned and modular JavaScript. They were exacerbated by my confusion about the plethora of module types and builds available.

The good news is that I got there in the end and am not using the Legacy build any more.

**Comment by yotamberk** [comment]
Glad to hear you've managed to work it out.

>The problems I failed to report in detail resulting in yotamberk's 'This issue is not exactly useful' comment were largely historical due to my use of Typescript, which did not at the time play well with a mix of old-fashioned and modular JavaScript. They were exacerbated by my confusion about the plethora of module types and builds available.

I don't fully understand what you mean here. I feel you have an issue with my response for the original issue submitted. I've answered as professionally as I can to a non-legitimate request.

Next time, if you need help, asking a legit request and/or giving detail on a problem will get you way farther then complaining about your personal issues...
