### ISSUE TITLE
[BUG][Timeline] Vertical scroll bug on groups column and timeline

### ISSUE THREAD

**Issue by gmcinalli** [visjs/vis-timeline#422]
Replicable here: https://visjs.github.io/vis-timeline/examples/timeline/other/verticalScroll.html

![Apr-08-2020 11-50-19](https://user-images.githubusercontent.com/9024983/78770782-59142c80-798f-11ea-8deb-22e8db82a251.gif)

As you can see, the two columns are detached by a click + drag, also there are graphic glitches by dragging the timeline directly.

**Comment by smee** [comment]
@yotamberk The jerky/jumping behaviour can indeed be seen in the verticalScroll demo. It seems to occur whenever the `center.height` has changed in line https://github.com/visjs/vis-timeline/blob/master/lib/timeline/Core.js#L1352

You can see this behaviour clearly when starting at the very top (drag the center down until the group "Truck 1" is visible), then click and hold the left mouse button on the center panel and slowly drag up. There is a clear jump when (still not visible) elements are added to the center DOM element.

**Comment by smee** [comment]
I don't fully understand the logic of the `_updateScrollTop()` function in https://github.com/visjs/vis-timeline/blob/master/lib/timeline/Core.js#L1350-L1372 but the comment implies, that it should react to changes in the container size, not the content. So would storing the previous container size and ignoring the size of the `center` dom element work?

**Comment by yotamberk** [comment]
I believe the jumping behavior and the detached groups column from the main content are two different issues.

The jumping behavior occurs due to the fact that group height is calculated dynamically by visible content. There is no real solution to this issue unless the rows are all the same heights (`stack: false` option) or somehow calculate column heights pre scrolling (or some other way that I simply don't see as feasible - I really tried in the past. The timeline used to load all the content and groups, and render them to the DOM even when not visible on screen, which does allow smooth scrolling since all the heights of the groups are known, but was affecting performance crucially. So this had to be changed to dynamic loading and height calculation, hence scroll jumping.)

In terms of the dragging detaching from the content, it is indeed an issue I think is caused due to the group scrollTop not being updated on the pan event. Scrolling does work so the logic is right, just not implemented in the pan/drag down and up events properly... It should be fixed.
If you want to give it a try, it will be more than welcomed.

**Comment by smee** [comment]
The jumping only occurs when clicking and dragging the center dom element. Using the left vertical scroll bar is smooth: no jumping whatsoever. So maybe investigating the differences between those two sources of vertical movement may give us a workaround?

**Comment by Dasandh** [comment]
Can anyone confirm that this was fixed? 
I still experience the same behavior in the demo, as well as in other projects, using 7.4.6.

**Comment by relanderolli** [comment]
> Hello, can anyone confirm that this was fixed?
> 
> I still experience the same behavior in the demo, as well as in other projects, using 7.4.6.

I’m still experiencing the same issue in version 7.7.3.
After debugging, the issue seems to occur only when dragging both horizontally and vertically simultaneously.
Vertical dragging works fine, which explains why scrolling works without issues.
